# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VLSI-RTL/asic_design/xilinx/soc_cm3/soc_cm3.cache/wt [current_project]
set_property parent.project_path D:/VLSI-RTL/asic_design/xilinx/soc_cm3/soc_cm3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VLSI-RTL/asic_design/xilinx/soc_cm3/soc_cm3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/CORTEXM3INTEGRATION/rtl/CORTEXM3INTEGRATIONDS.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_in.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_matrix.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_matrix_default_slave.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_matrix_lite.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_outM0.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_outM1.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_outM2.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cm3_outM3.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyArbiterNameM0.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyArbiterNameM1.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyArbiterNameM2.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyArbiterNameM3.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyDecoderNameS0.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyDecoderNameS1.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyDecoderNameS3.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyDecoderNameS4.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cm3_matrix/rtl/cmsdk_MyDecoderNameS5.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cmsdk_ahb_to_sram/rtl/cmsdk_ahb_to_sram.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cmsdk_fpga_sram/verilog/fpga_options_defs.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/cmsdk_fpga_sram/verilog/cmsdk_fpga_sram.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/CORTEXM3INTEGRATION/rtl/cortexm3ds_logic.v
  D:/VLSI-RTL/asic_design/xilinx/cortexm3_soc/top/rtl/cortexm3_soc.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cortexm3_soc -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cortexm3_soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cortexm3_soc_utilization_synth.rpt -pb cortexm3_soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
